name: Lean Action CI

on:
  push:
    branches:
      - main
      - nightly-testing
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          build-args: "--wfail --iofail"
          test-args: "--wfail --iofail"
      - name: "lake exe mk_all --check --module"
        run: |
          set -e
          lake exe mk_all --check --module
      - name: "lake shake"
        run: |
          set -e
          lake shake --add-public --keep-implied --keep-prefix Cslib
      - uses: leanprover-community/lint-style-action@main
        with:
          mode: check
